src/components/profile/team/GQLTeamCard.js
src/containers/Profile.js

Adding Tabs to the team card on the profile page

adding tabs to team card

---

i18n/en_CA/LC_MESSAGES/src/components/core/ProfileSearch.js.po
i18n/en_CA/LC_MESSAGES/src/components/profile/profileCard/GQLProfileCard.js.po
i18n/en_CA/LC_MESSAGES/src/components/profile/team/GQLTeamCard.js.po
i18n/en_CA/LC_MESSAGES/src/components/profile/team/TeamCardHolder.js.po
i18n/fr_CA/LC_MESSAGES/src/components/core/ProfileSearch.js.po
i18n/fr_CA/LC_MESSAGES/src/components/profile/profileCard/EditProfile.js.po
i18n/fr_CA/LC_MESSAGES/src/components/profile/profileCard/GQLProfileCard.js.po
i18n/fr_CA/LC_MESSAGES/src/components/profile/profileCard/ProfileCardDisplay.js.po
i18n/fr_CA/LC_MESSAGES/src/components/profile/team/GQLTeamCard.js.po
i18n/fr_CA/LC_MESSAGES/src/components/profile/team/TeamCardHolder.js.po
i18n/templates/src/components/core/ProfileSearch.js.pot
i18n/templates/src/components/profile/profileCard/GQLProfileCard.js.pot
i18n/templates/src/components/profile/team/GQLTeamCard.js.pot
i18n/templates/src/components/profile/team/TeamCardHolder.js.pot
src/components/core/ProfileSearch.js
src/components/profile/profileCard/GQLProfileCard.js
src/components/profile/team/GQLTeamCard.js
src/components/profile/team/TeamCardHolder.js

Translations

---

src/components/onboard/OnboardNav.js
src/components/profile/profileCard/EditProfile.js
src/components/profile/profileCard/GQLProfileCard.js
src/components/profile/profileCard/UserOptions.js
src/components/profile/profileCard/UserOptions.test.js
src/gql/profile.js

Various Layout changes.
Added UserOptions menu and mutation for possible later use.
Onboard Nav style will take effect when stylesheet cdn gets updated.

Layout changes

---

src/components/profile/OrgChart/Card/Card.js
src/components/profile/OrgChart/Card/__snapshots__/Card.stories.storyshot
src/components/profile/OrgChart/CardContainer/__snapshots__/CardContainer.stories.storyshot
src/components/profile/OrgChart/CardContainer/css/card_container.css
src/components/profile/OrgChart/MiniChart/__snapshots__/MiniChart.stories.storyshot
src/components/profile/OrgChart/MiniChart/css/MiniChart.css
src/components/profile/OrgChart/OrgChart/__snapshots__/OrgChart.stories.storyshot
src/components/profile/OrgChart/OrgChart/css/org_chart.css
src/components/profile/OrgChart/algorithm/__snapshots__/placement.stories.storyshot

Styling the orgchart
https://github.com/gctools-outilsgc/ux_prototypes/blob/master/Directory_Service/Directory_Final_Designs/US20_org_chart_miniprofile_v02.pdf

Orgchart styling

---

i18n/en_CA/LC_MESSAGES/src/components/core/ProgressBanner.js.po
i18n/fr_CA/LC_MESSAGES/src/components/core/ProgressBanner.js.po
i18n/templates/src/components/core/ProgressBanner.js.pot
src/components/core/ProgressBanner.js
src/containers/App.js
yarn.lock

Created component ProgressBanner to inform users the application is currently a proof of concept with randomly generated information in it.

Added info site banner

---

package.json
src/assets/css/index.css
src/components/profile/profileCard/EditProfile.js
src/components/profile/team/GQLTeamCard.js
src/components/profile/team/GQLYourTeamsTab.js
yarn.lock

Style changes and added font awesome package for icons.

Style and icons

---

i18n/en_CA/LC_MESSAGES/src/components/onboard/OnboardStep5.js.po
i18n/en_CA/LC_MESSAGES/src/components/profile/team/GQLTeamCard.js.po
i18n/fr_CA/LC_MESSAGES/src/components/onboard/OnboardStep5.js.po
i18n/fr_CA/LC_MESSAGES/src/components/profile/team/GQLTeamCard.js.po
i18n/templates/[filename].pot
src/components/onboard/OnboardStep5.js
src/components/profile/team/GQLTeamCard.js

Throw an error message when a user is trying to set themselves as their supervisor.

Stop user self report

---

i18n/en_CA/LC_MESSAGES/src/components/profile/profileCard/GQLYourInfoApprovalStatus.js.po
i18n/en_CA/LC_MESSAGES/src/components/profile/team/GQLYourApprovals.js.po
i18n/en_CA/LC_MESSAGES/src/components/profile/team/GQLYourTeamApprovalStatus.js.po
i18n/fr_CA/LC_MESSAGES/src/components/profile/profileCard/GQLYourInfoApprovalStatus.js.po
i18n/fr_CA/LC_MESSAGES/src/components/profile/team/GQLYourApprovals.js.po
i18n/fr_CA/LC_MESSAGES/src/components/profile/team/GQLYourTeamApprovalStatus.js.po
i18n/templates/[filename].pot
i18n/templates/src/components/profile/profileCard/GQLYourInfoApprovalStatus.js.pot
i18n/templates/src/components/profile/team/GQLYourTeamApprovalStatus.js.pot
src/assets/css/index.css
src/components/profile/profileCard/EditProfile.js
src/components/profile/profileCard/GQLProfileCard.js
src/components/profile/profileCard/GQLYourInfoApprovalStatus.js
src/components/profile/team/GQLTeamCard.js
src/components/profile/team/GQLYourTeamApprovalStatus.js
src/containers/App.js
src/gql/profile.js

Add component that let's users know that their sent approvals are pending, and gives them the option to revoke the approval. Mutation needs testing with updated backend.

WIP - Revoke approvals

---

src/components/profile/profileCard/EditProfile.js
src/components/profile/profileCard/ProfileCardDisplay.js
src/components/profile/team/GQLTeamCard.js
src/components/profile/team/TeamDisplayMemberList.js
src/components/profile/team/YourTeamMemberList.js
src/gql/profile.js

Added generic avatar to confirmation modal when user is changing their department through the edit form.

Adjust department change confirmation

---

i18n/en_CA/LC_MESSAGES/src/components/core/ProgressBanner.js.po
i18n/en_CA/LC_MESSAGES/src/components/core/SupervisorPicker.js.po
i18n/en_CA/LC_MESSAGES/src/components/onboard/OnboardStep1.js.po
i18n/en_CA/LC_MESSAGES/src/components/onboard/OnboardStep5.js.po
i18n/en_CA/LC_MESSAGES/src/components/profile/team/TeamCardHolder.js.po
i18n/en_CA/LC_MESSAGES/src/components/profile/team/TransferToSupervisorDialog.js.po
i18n/en_CA/LC_MESSAGES/src/containers/App.js.po
i18n/fr_CA/LC_MESSAGES/src/components/core/ProgressBanner.js.po
i18n/fr_CA/LC_MESSAGES/src/components/core/SupervisorPicker.js.po
i18n/fr_CA/LC_MESSAGES/src/components/onboard/OnboardStep1.js.po
i18n/fr_CA/LC_MESSAGES/src/components/onboard/OnboardStep5.js.po
i18n/fr_CA/LC_MESSAGES/src/components/profile/team/TeamCardHolder.js.po
i18n/fr_CA/LC_MESSAGES/src/components/profile/team/TransferToSupervisorDialog.js.po
i18n/fr_CA/LC_MESSAGES/src/containers/App.js.po
src/components/core/SupervisorPicker.js
src/components/onboard/OnboardNav.js
src/components/onboard/OnboardStep3.js
src/components/onboard/OnboardStep4.js
src/components/onboard/OnboardStep5.js
src/components/profile/team/TeamCardHolder.js
src/components/profile/team/TransferToSupervisorDialog.js
src/containers/App.js

Updated language and translations on various components in Directory. Also updated styles within onboarding components (Step counter now has "complete" class on completed steps).
Closes gctools-outilsgc/directory-fe#61 
Closes gctools-outilsgc/directory-fe#63 
Closes gctools-outilsgc/directory-fe#65

Update language + some styles

---

i18n/fr_CA/LC_MESSAGES/src/components/profile/team/GQLYourTeamsTab.js.po
src/components/profile/team/css/youTeamStyle.css

Adding some translation to the title and button.
Adding css top to image so all image are align with the div (team image)
related to https://zube.io/tbs-sct/gctools/c/5297

translation and css for transfert team function

---

src/components/home/CallToActionLinks.js
src/components/profile/profileCard/GQLProfileCard.js
src/components/profile/team/GQLYourTeamApprovalStatus.js

Fixed components displaying in wrong language on page load. The components that were effected by this were Profile header on profile page, CTA cards on main page, and approval status on profile page.
Closes #68

Fixed components displaying in wrong language on page load

---

package.json
src/components/profile/team/GQLTeamCard.js
src/components/profile/team/GQLYourTeamsTab.js

The front end app should now fail gracefully if the API returns a user without a team. (This should no longer occur in the API since updates but this is now in place on the off chance it does)
Also updated version of the i18n package
Fixes #17

Error handling when user has a null team

---

package.json
src/components/home/InfoText.js
src/index.js

Updating polyfill package in attempt to fix issues with app rendering in IE.

Updating polyfill package

---

i18n/en_CA/LC_MESSAGES/src/components/profile/profileCard/GQLProfileCard.js.po
i18n/fr_CA/LC_MESSAGES/src/components/profile/profileCard/GQLProfileCard.js.po
package.json
src/assets/css/index.css
src/components/profile/profileCard/GQLProfileCard.js
src/components/profile/team/TeamCardHolder.js
src/containers/Home.js
yarn.lock

Added heading elements to profile pages.
- Hidden h1 with the current profile name
- Card titles Profile and Team are now h2
Added react-helmet to directory-fe. The page title will now show Name - Directory instead of just Directory.
Removed extra main element from home page.

Changed a few structure elements on profile and home pages

---

Dockerfile

Adding steps to the Dockerfile to build and serve the app.

Quick patch to dockerfile to serve app

---

src/components/core/SupervisorPicker.js

Users who appear in the auto complete without an avatar will now show the generic avatar.

Add generic avatar to supervisorpicker list

---

docker-e2e/account-init/acc-init.sh
docker-e2e/account-init/start.sh
docker-e2e/docker-compose.yaml

Everything besides the front-end should initialize properly and connect to each other.
closes gctools-outilsgc/Kubernetes-config#34

E2e test back-end deployment

---

package.json
src/containers/App.js

When a user logs out, all elements on the page reflect that change.

Refresh page elements on logout

---

src/components/profile/team/TransferConfirmation.js

Fixes a layout issue with the transfer confirmation modal when transferring a user from team to team.

Team transfer confirmation modal display fix

---

src/components/core/ErrorModal.js
src/components/profile/profileCard/EditProfile.js

Added error state to edit profile components in order to reset the error messages.

Edit profile error modal

---

src/components/home/CallToActionLinks.js
src/components/profile/profileCard/GQLProfileCard.js
src/components/profile/team/GQLYourTeamApprovalStatus.js

Prevent infinite loop when toggling language

---

i18n/en_CA/LC_MESSAGES/src/components/core/DepartmentPicker.js.po
i18n/en_CA/LC_MESSAGES/src/components/core/SupervisorPicker.js.po
i18n/fr_CA/LC_MESSAGES/src/components/core/DepartmentPicker.js.po
i18n/fr_CA/LC_MESSAGES/src/components/core/SupervisorPicker.js.po
src/assets/css/index.css
src/components/core/DepartmentPicker.js
src/components/core/SupervisorPicker.js

Modifying the layout and style of department and supervisor selector components to make it clearer you need to select from the dropdown.
Needs translations.

Update department and supervisor selector components

---

src/components/profile/profileCard/ProfileCardDisplay.js

Org name only appeared in English, will now display correctly in French.

Translate org name on profile

---

i18n/en_CA/LC_MESSAGES/src/components/core/ErrorModal.js.po
i18n/fr_CA/LC_MESSAGES/src/components/core/ErrorModal.js.po
i18n/templates/src/components/core/ErrorModal.js.pot
src/components/core/ErrorModal.js

Adding support for error codes to translate the errors on the front end
Closes #112

WIP adding error code support to error modal

---

package.json
src/components/home/BlockCta.js
yarn.lock

Updated global-nav package to fix display issue that occurred when display width was 768px wide. Also adjusted columns on BlockCta component to have a cleaner appearance.
Closes #122

Small layout fixes

---

src/components/profile/profileCard/ProfileCardDisplay.js

Adding the ability to email, call and get the googlemaps page in one click / tape
I have to change how the address work by creating only one big condition on addressUser instead of a condition on each field.
Issue: https://zube.io/tbs-sct/gctools/c/5919

Adding link to profile information

---

i18n/en_CA/LC_MESSAGES/src/containers/Search.js.po
i18n/fr_CA/LC_MESSAGES/src/containers/Search.js.po
src/assets/css/index.css
src/components/core/ProfileSearch.js
src/containers/App.js
src/containers/Search.js

Related to: https://zube.io/tbs-sct/gctools/c/5894 and https://zube.io/tbs-sct/gctools/c/5893
Adding the search icon to the search input with the redirect to the user or to the search page if the dropdown have more than one user.
On the search page you have the ability to sort the list or to search again.
On the right side, a filter box is there but do not work since we do not have a lot of information from the search result.

Adding a search page and an icon to the search bar

---

src/components/profile/team/GQLYourTeamsTab.js
src/components/profile/team/css/youTeamStyle.css

Added an arrow indicator to the new accordion modal to add clarity.

Adding accordion arrow style change

---

i18n/en_CA/LC_MESSAGES/src/components/process/GQLApproveApproval.js.po
i18n/en_CA/LC_MESSAGES/src/components/process/GQLDenyApproval.js.po
i18n/fr_CA/LC_MESSAGES/src/components/process/GQLApproveApproval.js.po
i18n/fr_CA/LC_MESSAGES/src/components/process/GQLDenyApproval.js.po
src/components/process/GQLApproveApproval.js
src/components/process/GQLDenyApproval.js
src/containers/App.js
src/containers/ProcessApproval.js
src/gql/profile.js

Adds new pages to Directory to allow quick approve/deny of approvals through links provided to them in their email.
Related to https://github.com/gctools-outilsgc/profile_service/pull/81

Adding quick approval workflow options.

---

i18n/en_CA/LC_MESSAGES/src/containers/Search.js.po
i18n/fr_CA/LC_MESSAGES/src/containers/Search.js.po
src/components/search/Pagination.js
src/containers/Search.js

Adding drop down to increase the number of results displayed per page.
Closes #141

Adding results per page select

---

i18n/en_CA/LC_MESSAGES/src/components/profile/team/GQLYourApprovals.js.po
i18n/fr_CA/LC_MESSAGES/src/components/profile/team/GQLYourApprovals.js.po
src/components/profile/team/GQLYourApprovals.js

Updating the approvals tab UI for desktop and mobile.

Modify approvals UI

---

src/assets/css/index.css
src/components/search/Pagination.js
src/components/search/filters.js
src/containers/Search.js

Base on the design create in https://zube.io/tbs-sct/gctools/c/6102
Create a button on small screen to get the filter menu.
Reduce the number of pagination to only two before and after the current page.
Limite the number of character in the email.
ReOrganize the profile cart layout.
Fix issue https://zube.io/tbs-sct/gctools/c/6160

Mobile layout for the search page

---

src/containers/Search.js

Adding the ability to get the french name of team and organization when french language is selected.
Fixing #149

Add team and organization translation
